#https://github.com/sergiolombana101

language: node_js

node_js:
  - "10.9.0"

cache: npm

env:
  - NOW_TOKEN="VRihodwu81gcAWzokpySNczc"

before_install:
  - ls -la

install:
  - npm install

script:
  - npm run build
  - npm run test